version: 2

jobs:
  build:
    working_directory: /app

    docker:
      - image: docker.io/golang:1.12

    steps:
      - checkout

      - run:
          name: Deps
          command: go mod download

      - run:
          name: Compile
          command: go build -v

      - run:
          name: Check formatting
          command: diff -u <(echo -n) <(gofmt -s -d .)

      - run:
          name: Test
          command: go test
